<?php
// This file is part of Moodle - https://moodle.org/.
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Restore integration for the plugin.
 *
 * @package    local_courseqbankcopy
 * @copyright  2026 jPerpetuo <joao.ariel@crearenet.com.br>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
use local_courseqbankcopy\local\operation_repository;
use local_courseqbankcopy\local\runtime_registry;

/**
 * Persists the mappings generated by Moodle while restoring the import.
 */
class restore_local_courseqbankcopy_plugin extends restore_local_plugin {
    /** @var array<string, bool> */
    private static array $statusset = [];

    /** @var array<string, bool> */
    private static array $seenmodules = [];

    /** @var array<string, bool> */
    private static array $seenqbes = [];

    /** @var array<string, bool> */
    private static array $seencategories = [];

    /**
     * Defines the course-module marker path.
     *
     * @return restore_path_element[]
     */
    protected function define_module_plugin_structure(): array {
        return [new restore_path_element(
            $this->get_namefor('module_marker'),
            $this->get_pathfor('/module_marker'),
        )];
    }

    /**
     * Defines the question marker path.
     *
     * @return restore_path_element[]
     */
    protected function define_question_plugin_structure(): array {
        return [new restore_path_element(
            $this->get_namefor('question_marker'),
            $this->get_pathfor('/question_marker'),
        )];
    }

    /**
     * Saves the old-to-new course-module mapping.
     *
     * @param array $data Marker data.
     */
    public function process_local_courseqbankcopy_module_marker(array $data): void {
        $restoreid = $this->get_restoreid();
        if (!$this->is_managed_restore($restoreid)) {
            return;
        }

        $this->mark_restoring($restoreid);
        $mappingkey = $restoreid . ':' . (int) $data['sourcecmid'];
        if (isset(self::$seenmodules[$mappingkey])) {
            return;
        }
        self::$seenmodules[$mappingkey] = true;
        operation_repository::upsert_mapping(
            $restoreid,
            operation_repository::TYPE_MODULE,
            (int) $data['sourcecmid'],
            (int) $this->get_task()->get_moduleid(),
        );
    }

    /**
     * Saves question-bank-entry and category mappings after the question exists.
     *
     * @param array $data Marker data.
     */
    public function process_local_courseqbankcopy_question_marker(array $data): void {
        global $DB;

        $restoreid = $this->get_restoreid();
        if (!$this->is_managed_restore($restoreid)) {
            return;
        }

        $this->mark_restoring($restoreid);

        $newquestionid = (int) $this->get_mappingid('question', (int) $data['sourcequestionid']);
        if (!$newquestionid) {
            return;
        }

        $newrecord = $DB->get_record_sql(
            "SELECT qv.questionbankentryid, qbe.questioncategoryid, qc.contextid
               FROM {question_versions} qv
               JOIN {question_bank_entries} qbe ON qbe.id = qv.questionbankentryid
               JOIN {question_categories} qc ON qc.id = qbe.questioncategoryid
              WHERE qv.questionid = ?",
            [$newquestionid],
            MUST_EXIST,
        );

        $qbekey = $restoreid . ':' . (int) $data['sourceqbeid'];
        if (!isset(self::$seenqbes[$qbekey])) {
            self::$seenqbes[$qbekey] = true;
            operation_repository::upsert_mapping(
                $restoreid,
                operation_repository::TYPE_QBE,
                (int) $data['sourceqbeid'],
                (int) $newrecord->questionbankentryid,
                (int) $data['sourcecategoryid'],
                (int) $newrecord->questioncategoryid,
            );
        }

        $categorykey = $restoreid . ':' . (int) $data['sourcecategoryid'];
        if (!isset(self::$seencategories[$categorykey])) {
            self::$seencategories[$categorykey] = true;
            operation_repository::upsert_mapping(
                $restoreid,
                operation_repository::TYPE_CATEGORY,
                (int) $data['sourcecategoryid'],
                (int) $newrecord->questioncategoryid,
                (int) $data['sourcecontextid'],
                (int) $newrecord->contextid,
            );
        }
    }

    /**
     * Checks whether this restore was prepared by the interceptor.
     *
     * @param string $restoreid Restore ID.
     * @return bool
     */
    private function is_managed_restore(string $restoreid): bool {
        if (runtime_registry::get_restoreid() === $restoreid) {
            return true;
        }
        if (!operation_repository::get($restoreid)) {
            return false;
        }
        runtime_registry::set_restoreid($restoreid);
        return true;
    }

    /**
     * Changes the operation to restoring once per PHP request.
     *
     * @param string $restoreid Restore ID.
     */
    private function mark_restoring(string $restoreid): void {
        if (isset(self::$statusset[$restoreid])) {
            return;
        }
        self::$statusset[$restoreid] = true;
        operation_repository::set_status($restoreid, operation_repository::STATUS_RESTORING);
    }
}
